### ISSUE TITLE
start versionin the libraries

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#129] opened 2013-02-08 08:26 UTC
- we still have soname 0.0.1 and already ran into a few problems when changing API/ABI and not changing the soname

**Comment by xsuchy** [comment] 2020-04-09 21:57
we have versioned soname nowadays.

**Comment by ernestask** [comment] 2020-04-09 22:00
That’s not what the issue is about. The original comment already states that we use 0.0.1.

**Comment by ernestask** [comment] 2020-04-09 22:02
Every other release we do breaks binary compatibility and we still ship libreport.so.0.

**Comment by xsuchy** [comment] 2020-06-10 08:31
Resolved in https://github.com/abrt/libreport/pull/635

**Closed by xsuchy** 2020-06-10 08:31 UTC
Labels: enhancement
