### ISSUE TITLE
libreport-2.9.0 fails to compile: _pyreport.ver:2: syntax error in VERSION script

### ISSUE THREAD

**Issue by pacho2** [abrt/libreport#478] opened 2017-02-11 15:50 UTC
I get this:
Making all in plugins
make[3]: Entering directory '/hdd/home/pacho/Descargas/libreport-2.9.0/src/plugins'
  CC       reporter_bugzilla-reporter-bugzilla.o
  CC       reporter_bugzilla-rhbz.o
  CCLD     reporter-bugzilla
  CC       report-report.o
  CCLD     report
  CC       reporter_mantisbt-reporter-mantisbt.o
  CC       reporter_mantisbt-mantisbt.o
  CCLD     reporter-mantisbt
  CC       reporter_ureport-reporter-ureport.o
  CCLD     reporter-ureport
  CC       reporter_rhtsupport-abrt_rh_support.o
  CC       reporter_rhtsupport-reporter-rhtsupport-parse.o
  CC       reporter_rhtsupport-reporter-rhtsupport.o
  CCLD     reporter-rhtsupport
  CC       reporter_kerneloops-reporter-kerneloops.o
  CCLD     reporter-kerneloops
  CC       reporter_upload-reporter-upload.o
  CCLD     reporter-upload
  CC       reporter_mailx-reporter-mailx.o
  CCLD     reporter-mailx
  CC       reporter_print-reporter-print.o
  CCLD     reporter-print
  CC       reporter_systemd_journal-reporter-systemd-journal.o
  CCLD     reporter-systemd-journal
  ITMRG  report_Bugzilla.xml
make[3]: Leaving directory '/hdd/home/pacho/Descargas/libreport-2.9.0/src/plugins'
Making all in report-python
make[3]: Entering directory '/hdd/home/pacho/Descargas/libreport-2.9.0/src/report-python'
  CC       _py3report_la-reportmodule.lo
  CC       _py3report_la-problem_data.lo
  CC       _py3report_la-dump_dir.lo
  CC       _py3report_la-run_event.lo
  CC       _py3report_la-report.lo
  CCLD     _py3report.la
  CC       _pyreport_la-reportmodule.lo
  CC       _pyreport_la-problem_data.lo
  CC       _pyreport_la-dump_dir.lo
  CC       _pyreport_la-run_event.lo
  CC       _pyreport_la-report.lo
  CCLD     _pyreport.la
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld:.libs/_pyreport.ver:2: syntax error in VERSION script
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:641: _pyreport.la] Error 1
make[3]: Leaving directory '/hdd/home/pacho/Descargas/libreport-2.9.0/src/report-python'
make[2]: *** [Makefile:470: all-recursive] Error 1
make[2]: Leaving directory '/hdd/home/pacho/Descargas/libreport-2.9.0/src'
make[1]: *** [Makefile:611: all-recursive] Error 1
make[1]: Leaving directory '/hdd/home/pacho/Descargas/libreport-2.9.0'
make: *** [Makefile:497: all] Error 2

**Comment by pacho2** [comment] 2017-02-19 11:23
The contents of the file are:
{ global:
local: *; };

**Comment by mhabrnal** [comment] 2017-02-21 09:59
What is your compilation workflow?
I tied it and it worked for me.

You can find some information in the following link:
https://github.com/abrt/abrt/blob/master/INSTALL.md
```
...
make[3]: Leaving directory '/home/mhabrnal/fed/libreport/libreport-2.9.0/src/plugins'
Making all in report-python
make[3]: Entering directory '/home/mhabrnal/fed/libreport/libreport-2.9.0/src/report-python'
  CC       _py3report_la-reportmodule.lo
  CC       _py3report_la-problem_data.lo
  CC       _py3report_la-dump_dir.lo
  CC       _py3report_la-run_event.lo
  CC       _py3report_la-report.lo
  CCLD     _py3report.la
  CC       _pyreport_la-reportmodule.lo
  CC       _pyreport_la-problem_data.lo
  CC       _pyreport_la-dump_dir.lo
  CC       _pyreport_la-run_event.lo
  CC       _pyreport_la-report.lo
  CCLD     _pyreport.la
make[3]: Leaving directory '/home/mhabrnal/fed/libreport/libreport-2.9.0/src/report-python'
Making all in cli
...
```

**Comment by pacho2** [comment] 2017-02-21 20:05
I am simply running:
./configure && make

and it fails :/
[config.log.txt](https://github.com/abrt/libreport/files/791373/config.log.txt)

**Comment by pacho2** [comment] 2017-02-21 20:06
I am building from the tarball at https://fedorahosted.org/released/abrt/

**Comment by mhabrnal** [comment] 2017-02-22 12:24
I've downloaded 
`https://fedorahosted.org/released/abrt/libreport-2.9.0.tar.gz` 
extracted the tarball and ran 
`./configure && make`
everything worked for me on Fedora Rawhide.

What system are you using?

**Comment by pacho2** [comment] 2017-02-25 11:55
It is Gentoo in my case :/ 

the offending file contains the same for your case when compiling on Fedora?

**Comment by xsuchy** [comment] 2017-05-11 08:53
Gentoo is not supported by core maintainers. So I am really afraid you are on your own.

**Comment by jfilak** [comment] 2017-05-23 05:51
I have seen this kind of error on Fedora too but I cannot remember how I fixed it, but something says me that the issue is caused by insufficient initialization of autotools - `./atogen.sh && ./configure`.

**Comment by xsuchy** [comment] 2020-04-09 21:35
Closing as it is likely nothing happens in the future about this issue.

**Closed by xsuchy** 2020-04-09 21:35 UTC
Labels: on hold
