### ISSUE TITLE
reporter-bugzilla segfaults when the format files are missing

### ISSUE THREAD

**Issue by mmilata** [abrt/libreport#162] opened 2013-05-31 13:07 UTC
(happens e.g. when you try to run reporter-bugzilla from its build directory without installing it)

To reproduce:

```
% reporter-bugzilla -c ./bugzilla.conf -d ~/ccpp-not-a-duplicate -F /dev/null -A /dev/null
Logging into Bugzilla at https://partner-bugzilla.redhat.com
Checking for duplicates
Creating a new bug
zsh: segmentation fault  reporter-bugzilla -c ./bugzilla.conf -d ~/ccpp-not-a-duplicate -F /dev/null -A /dev/null
```

**Comment by ernestask** [comment] 2018-11-19 11:59
Cannot reproduce, no stack trace provided, closing.

**Closed by ernestask** 2018-11-19 11:59 UTC
Labels: bug
